---

- name: Ensure data dir exists
  file: name=/var/grafana state=directory owner=472 mode=0755

- name: Ensure docker container is running
  docker_container:
    name: grafana
    image: grafana/grafana
    state: started
    pull: true
    volumes:
      - "/var/grafana:/var/lib/grafana"
    ports:
      - "127.0.0.1:3000:3000"
    env:
      GF_SERVER_ROOT_URL: "{{ grafana.fqdn }}"
      GF_SECURITY_ADMIN_PASSWORD: "{{ grafana.admin_pass }}"
    restart_policy: always

