- name: Restart fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: Reload sysctl
  shell: sysctl --system

- name: Restart auditd
  systemd:
    name: auditd
    state: restarted

- name: Restart sysstat 
  systemd:
    name: sysstat
    state: restarted
