- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Reload sysctl
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted

- name: Restart sysstat 
  ansible.builtin.systemd:
    name: sysstat
    state: restarted
