- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Reload sysctl
  ansible.builtin.command: sysctl --system

- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted

- name: Restart sysstat
  ansible.builtin.systemd:
    name: sysstat
    state: restarted
