---
- hosts: routers
  roles:
    - packages
    - users
    - ssh
    - interfaces
    - forwarding
    - iptables
    - rc_local
    - routinator
    - routing
    - node_exporter
    - bird_exporter
    - wireguard
    - { role: dhcp, when: dhcp is defined }
    - tcp-bbr
