---

- name: Install rpmfusion
  shell: dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

- name: Install packages
  dnf: 
    name: "{{ packages_fedora }}" 
    state: present
