- name: Ensure config dir exists
  file: path=/etc/promtail mode=0755 owner=root state=directory

- name: Ensure config file is up to date
  template: src=config.yml.j2 dest=/etc/promtail/config.yml owner=root mode=0644

- name: Ensure docker python binding is installed
  pip: name=docker state=present

- name: Ensure docker container is running
  docker_container:
    name: promtail
    image: grafana/promtail:master
    state: started
    pull: true
    volumes:
      - "/var/log:/var/log"
      - "/etc/promtail/config.yml:/etc/promtail/docker-config.yaml"
    restart_policy: always
    command: "-config.file=/etc/promtail/docker-config.yaml"
