- name: Ensure newest caddy version is installed
  ansible.builtin.shell: "{{ go_path }}/go get -u github.com/mholt/caddy/caddy"
  environment:
    GOPATH: /usr/local
  tags:
    - upgrade
  notify: Restart caddy

- name: Ensure caddy user exists
  ansible.builtin.user:
    name: caddy
    system: yes

- name: Ensure caddy config directory exists
  ansible.builtin.file: 
    path: /etc/caddy 
    owner: caddy 
    mode: 0500 
    state: directory 

- name: Ensure CADDYPATH directory exists
  ansible.builtin.file: 
    path: /var/caddy 
    owner: caddy 
    mode: 0700 
    state: directory 

- name: Ensure caddy is configured 
  ansible.builtin.template: 
    src: Caddyfile.j2 
    dest: /etc/caddy/Caddyfile 
    owner: caddy 
    mode: 0400
  notify: Restart caddy

- name: Ensure service unit exists
  ansible.builtin.copy: 
    src: caddy.service
    dest: /lib/systemd/system/caddy.service
    mode: 0644
    owner: root
  register: systemd
  notify: Restart caddy

- name: Reload systemd
  ansible.builtin.systemd: 
    daemon_reload: yes
  when: systemd.changed
