- name: Ensure newest caddy version is installed
  shell: "{{ go_path }}/go get -u github.com/mholt/caddy/caddy"
  environment:
    GOPATH: /usr/local
  tags:
    - upgrade
  notify: Restart caddy

- name: Ensure caddy user exists
  user:
    name: caddy
    system: yes

- name: Ensure caddy config directory exists
  file: 
    path: /etc/caddy 
    owner: caddy 
    mode: 0500 
    state: directory 

- name: Ensure CADDYPATH directory exists
  file: 
    path: /var/caddy 
    owner: caddy 
    mode: 0700 
    state: directory 

- name: Ensure caddy is configured 
  template: 
    src: Caddyfile.j2 
    dest: /etc/caddy/Caddyfile 
    owner: caddy 
    mode: 0400
  notify: Restart caddy

- name: Ensure service unit exists
  copy: src=caddy.service dest=/lib/systemd/system/caddy.service mode=0644 owner=root
  register: systemd
  notify: Restart caddy

- name: Reload systemd
  systemd: 
    daemon_reload: yes
  when: systemd.changed
