- name: Ensure core dumps are disabled (profile)
  ansible.builtin.copy:
    content: "#!/bin/sh\nulimit -c 0"
    dest: /etc/profile.d/disable-coredumps.sh
    owner: root
    mode: '644'

- name: Ensure core dumps are disabled (limits)
  ansible.builtin.copy:
    content: "* hard core 0"
    dest: /etc/security/limits.d/disable-coredumps
    owner: root
    mode: '644'
