- name: Ensure correct permissions for system files
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: '600'
  with_items:
    - /etc/crontab
    - /boot/grub2/grub.cfg
    - /etc/ssh/sshd_config
    - /etc/at.deny

- name: Ensure root .ssh dir is not accessible
  ansible.builtin.file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: '700'

- name: Ensure home dirs are not accessible by world
  ansible.builtin.shell: find /home/* -maxdepth 0 -type d | xargs -I {} chmod 750 {}

- name: Ensure cron directories are not accessible by world
  ansible.builtin.file:
    path: "/etc/{{ item }}"
    state: directory
    owner: root
    mode: '700'
  with_items:
    - cron.d
    - cron.daily
    - cron.hourly
    - cron.weekly
    - cron.monthly
