- name: Ensure hosts file is correct
  ansible.builtin.template:
    src: hosts.j2
    dest: /etc/hosts

- name: Ensure legal banner exists
  ansible.builtin.template:
    src: issue.j2
    dest: /etc/issue

- name: Ensure issue.net does not exist
  ansible.builtin.file:
    path: /etc/issue.net
    state: absent

- ansible.builtin.include: updates.yml

- ansible.builtin.include: tools.yml

- ansible.builtin.include: file-permissions.yml

- ansible.builtin.include: coredump.yml

- ansible.builtin.include: kernel.yml

- ansible.builtin.include: compilers.yml

