- name: Ensure security relevant tools are installed
  ansible.builtin.dnf:
    name:
      - fail2ban
      - sysstat
      - rkhunter
      - libpwquality
      - openscap-scanner
    state: present

- name: Ensure fail2ban is configured
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: 644
  notify: Restart fail2ban

- name: Ensure auditd is configured
  ansible.builtin.copy:
    src: audit.rules
    dest: /etc/audit/rules.d/log-root.rules
    owner: root
    group: root
    mode: '600'
  notify: Restart auditd

- name: Ensure system is enabled
  ansible.builtin.copy:
    content: 'ENABLED=”true”'
    dest: /etc/default/sysstat
  notify: Restart sysstat

- name: Ensure sysstat daemon is enabled
  ansible.builtin.systemd:
    name: sysstat
    state: started
    enabled: true
