- name: Ensure dnf-automatic is installed
  ansible.builtin.dnf:
    name: dnf-automatic
    state: present

- name: Ensure dnf-automatic is configured
  ansible.builtin.copy:
    src: dnf-automatic.conf
    dest: /etc/dnf/automatic.conf
    owner: root
    mode: '600'

- name: Ensure dnf-automatic is enabled and running
  ansible.builtin.systemd:
    name: dnf-automatic.timer
    enabled: true
