- name: Ensure iptables is installed
  dnf: 
    name: iptables-services
    state: present

- name: Ensure iptables is configured
  template: 
    src: iptables.rules.j2 
    dest: /etc/sysconfig/iptables.rules 
    mode: 0600 
    owner: root
  notify: Reload iptables

- name: Ensure ip6tables is configured
  template: 
    src: ip6tables.rules.j2 
    dest: /etc/sysconfig/ip6tables.rules 
    mode: 0600 
    owner: root
  notify: Reload ip6tables

- name: Ensure iptables is enabled and started
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
  - iptables
  - ip6tables
