- name: Ensure iptables is installed
  ansible.builtin.dnf:
    name: iptables-services
    state: present

- name: Ensure iptables is configured
  ansible.builtin.template:
    src: iptables.rules.j2 
    dest: /etc/sysconfig/iptables 
    mode: '600' 
    owner: root
  notify: Reload iptables

- name: Ensure ip6tables is configured
  ansible.builtin.template:
    src: ip6tables.rules.j2 
    dest: /etc/sysconfig/ip6tables 
    mode: '600' 
    owner: root
  notify: Reload ip6tables

- name: Ensure iptables is enabled and started
  ansible.builtin.systemd:
    name: "{{ item }}"
    enabled: true
    state: started
  with_items:
    - iptables
    - ip6tables
