---

- name: Ensure iptables is configured
  template: src=iptables.rules.j2 dest=/etc/sysconfig/iptables.rules mode=0644 owner=root
  notify: Reload iptables

- name: Ensure ip6tables is configured
  template: src=ip6tables.rules.j2 dest=/etc/sysconfig/ip6tables.rules mode=0644 owner=root
  notify: Reload ip6tables
