- name: Ensure post up service for {{ iface.name }} exists
  ansible.builtin.template:
    src: service.j2
    dest: /etc/systemd/system/post-up-{{ iface.name }}.service
    owner: root
    mode: '444'
