- name: Ensure loopback is configured
  template: 
    src: loopback.network.j2 
    dest: /etc/systemd/network/10-loopback.network 
    mode: 0444 
    owner: root
  notify: Restart network

- name: Ensure physical interfaces are configured 
  template: 
    src: network.j2 
    dest: "/etc/systemd/network/20-{{ iface.name }}.network" 
    mode: 0444 
    owner: root
  loop: "{{ interfaces }}"
  loop_control:
    loop_var: "iface"
  notify: Restart network

- name: Ensure VLAN interfaces are configured 
  template: 
    src: vlan.j2 
    dest: "/etc/systemd/network/20-{{ item[1].name }}.netdev" 
    mode: 0444 
    owner: root
  vars:
    iface: "{{ item[1] }}"
  loop: "{{ interfaces | subelements('vlans') }}"
  notify: Restart network

- template: 
    src: network.j2 
    dest: "/etc/systemd/network/30-{{ item[1].name }}.network" 
    mode: 0444 
    owner: root
  vars:
    iface: "{{ item[1] }}"
    is_vlan: true
  loop: "{{ interfaces | subelements('vlans') }}"
  notify: Restart network
