- name: Ensure kea is installed
  ansible.builtin.dnf:
    name: kea

- name: Ensure key var directory exists
  ansible.builtin.file:
    path: /var/kea
    state: directory
    mode: 0755
    owner: root

- name: Ensure config is up to date
  ansible.builtin.template:
    src: kea.conf.j2
    dest: /etc/kea/kea-dhcp4.conf
    owner: root
    mode: 0644
  notify: Restart kea

- name: Ensure service is enabled and running
  ansible.builtin.systemd:
    name: kea-dhcp4
    state: started
    enabled: yes
