- name: Get kernel version
  shell: uname -r
  register: kernel_version

- name: Check for bbr support
  shell: egrep "CONFIG_TCP_CONG_BBR=(m|y)" /boot/config-{{ kernel_version.stdout }}
  register: bbr_support
  ignore_errors: yes

- name: Ensure sysctl is configured
  copy: 
    src: 90-bbr.conf 
    dest: /etc/sysctl.d/90-bbr.conf 
    mode: 0400 
    owner: root
  notify: Reload sysctl
  when: bbr_support | succeeded

