- name: Create systemd unit
  copy: src=systemd.service dest=/etc/systemd/system/node_exporter.service
  register: systemd_unit

- name: Reload systemd
  systemd: daemon_reload=yes
  when: systemd_unit.changed

- name: Start node-exporter
  service: name=node_exporter state=started enabled=yes
