- name: Ensure newest version of node exporter is installed
  ansible.builtin.shell: "{{ go_path }}/go get github.com/prometheus/node_exporter"
  environment:
    GOPATH: /usr/local

- name: Create systemd unit
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/node_exporter.service
  register: systemd_unit

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  when: systemd_unit.changed

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    name: node_exporter
    state: started
    enabled: yes
