---

- name: Ensure newest version of node exporter is installed
  shell: "{{ go_path }}/go get github.com/prometheus/node_exporter"
  environment: 
    GOPATH: /usr/local
    GO15VENDOREXPERIMENT: 1 

- stat: path=/bin/systemctl
  register: systemd

- include_tasks: configure_initd.yml
  when: not systemd.stat.exists

- include_tasks: configure_systemd.yml
  when: systemd.stat.exists    
