- name: Create groups
  ansible.builtin.group:
    name: "{{ item }}"
  with_items: "{{ user_groups }}"

- name: Create user account
  ansible.builtin.user:
    name: "{{ user.name }}"
    groups: "{{ user.groups | join(',') }}" 
    createhome: yes
    shell: "{{ user.shell }}"
    comment: "{{ user.comment }}"
    home: "/home/{{ user.name }}"

- name: Set authorized_keys
  ansible.builtin.authorized_key:
    user: "{{ user.name }}" 
    key: "{{ item }}"
  with_items: "{{ user.ssh_keys }}"
