---

- name: Ensure build requirements are met
  dnf: name={{ item }} state=present
  with_items:
    - flex
    - bison
    - ncurses-devel
    - readline-devel

- name: Ensure build dir does not exist
  file: path=/tmp/bird state=absent

- name: Extract source code
  unarchive:
    src: "/usr/src/bird-{{ bird_version }}.tar.gz"
    dest: /tmp
    remote_src: true

- name: Configure bird build
  shell: cd /tmp/bird-{{ bird_version }} && ./configure --sysconfdir=/etc/bird

- make:
    chdir: "/tmp/bird-{{ bird_version }}"
    target: clean

- name: Build bird
  make:
    chdir: "/tmp/bird-{{ bird_version }}"

- name: Install bird
  make:
    chdir: "/tmp/bird-{{ bird_version }}"
    target: install
