---

- name: Ensure systemd units exist
  copy: src={{ service_name }}.service dest=/lib/systemd/system/{{ service_name }}.service
  register: service_unit

- name: Reload systemd configuration
  shell: systemctl daemon-reload
  when: service_unit.changed

- name: Enable service
  service: name={{ service_name }} enabled=yes

- name: Start if not started yet
  service: name={{ service_name }} state=started
