---

- name: Ensure bird packages are uninstalled
  dnf: name={{ item }} state=absent
  with_items:
    - bird
    - bird6

- name: Check if source has changed
  get_url: url="ftp://bird.network.cz/pub/bird/bird-{{ bird_version }}.tar.gz" dest="/usr/src/bird-{{ bird_version }}.tar.gz"
  register: bird_source

- include_tasks: 'build_bird.yml'
  when: bird_source.changed
  
- name: Ensure rsyslog config exists
  copy: src=bird_rsyslog.conf dest=/etc/rsyslog.d/bird.conf mode=0644 owner=root
  notify: Restart rsyslog

- name: Ensure logrotate config exists
  copy: src=bird_logrotate dest=/etc/logrotate.d/bird mode=0644 owner=root
