
- name: Ensure bird_exporter is installed
  environment:
    GOPATH: /usr/local
  shell: go get -u github.com/czerwonk/bird_exporter
  notify: Restart bird_exporter

- name: Ensure service is configured
  copy: 
    src: bird_exporter.service 
    dest: /lib/systemd/system/bird_exporter.service
  register: service_unit

- name: Reload systemd
  systemd: 
    daemon_reload: yes
  when: service_unit.changed

- name: Ensure service is enabled and started
  service: 
    name: bird_exporter 
    enabled: yes
    state: started
