---

- name: Extract source code
  unarchive: 
    src: /usr/src/jool-{{ jool_version }}.zip
    dest: /usr/src
    remote_src: true

- name: Install module
  shell: dkms install /usr/src/jool-{{ jool_version }}

- name: Configure userland tool build
  shell: cd /usr/src/jool-{{ jool_version }} && ./configure

- name: Install userland tools
  make:
    chdir: /usr/src/jool-{{ jool_version }}
    target: install
