---

- name: Ensure bind is installed
  dnf: name=bind state=installed

- name: Ensure cache directory exists
  file: path=/var/cache/bind state=directory owner=named mode=0755

- name: Ensure bind is configured
  template: src=named.conf.j2 dest=/etc/named.conf
  notify: Restart bind

- name: Ensure service is enabled
  service: name=named enabled=yes

- name: Ensure service is started
  service: name=named state=started
