---

- name: Download newest version
  get_url: url=https://github.com/NICMx/Jool/releases/download/v{{ jool_version }}/jool_{{ jool_version }}.tar.gz dest=/usr/src/jool-{{ jool_version }}.zip
  register: jool_sources

- include_tasks: 'build_jool.yml'
  when: jool_sources.changed

- name: Ensure module is configured
  copy: dest=/etc/modules-load.d/jool.conf content="jool pool6=64:ff9b::/96" mode=0644 owner=root

- name: Ensure kernel module is started
  shell: modprobe jool pool6=64:ff9b::/96

