---

- name: Download newest version
  get_url: url=https://github.com/NICMx/Jool/releases/download/v{{ jool_version }}/jool_{{ jool_version }}.tar.gz dest=/usr/src/jool-{{ jool_version }}.zip
  register: jool_sources

- include_tasks: 'build_jool.yml'
  when: jool_sources.changed

- name: Ensure module is configured
  copy: dest=/etc/modules-load.d/jool.conf content="jool" mode=0644 owner=root

- name: Ensure kernel module is started
  shell: modprobe jool

- name: Ensure service is installed
  template: src=jool.service.j2 dest=/lib/systemd/system/jool.service mode=0644 owner=root
  register: systemd

- name: Relaod systemd
  systemd: daemon_reload=yes
  when: systemd.changed

- name: Ensure jool is enabled and started
  systemd: name=jool enabled=yes state=started
