- name: Create TAL directory
  file: path=/etc/routinator/tals state=directory owner=root mode=0755

- name: Ensure ARIN TAL exists
  get_url: url=https://www.arin.net/resources/manage/rpki/arin-rfc7730.tal dest=/etc/routinator/tals/arin.tal

- name: Ensure other TALs exist
  get_url: url=https://raw.githubusercontent.com/NLnetLabs/routinator/master/tals/{{ item }}.tal dest=/etc/routinator/tals/
  with_items:
  - ripe
  - afrinic
  - apnic
  - lacnic

- name: Ensure routinator is configured
  docker_container:
    name: routinator
    image: nlnetlabs/routinator
    ports:
    - "127.0.0.1:3323:3323"
    restart_policy: always
    state: started
    volumes:
    - /etc/routinator/tals/:/root/.rpki-cache/tals/
