- name: Ensure image is pulled
  docker_image:
    name: nlnetlabs/routinator
    source: pull

- name: Ensure volume exists
  docker_volume:
    name: routinator-tals
  register: volume_created

- name: Ensure TALS are present
  shell: docker run --rm -v routinator-tals:/home/routinator/.rpki-cache/tals nlnetlabs/routinator init -f --accept-arin-rpa
  when: volume_created.changed

- name: Ensure routinator is running
  docker_container:
    name: routinator
    image: nlnetlabs/routinator
    ports:
    - "127.0.0.1:3323:3323"
    restart_policy: always
    state: started
    volumes:
    - routinator-tals:/home/routinator/.rpki-cache/tals
