- name: Ensure docker is installed
  dnf: 
    name: 
    - moby-engine 
    state: present

- name: Ensure docker is configured
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json

- name: Ensure docker daemon is enabled and running
  service: 
    name: docker 
    state: started
    enabled: yes
  
