- name: Ensure wireguard is installed
  ansible.builtin.dnf: 
    name: wireguard-tools
    state: present

- name: Ensure config dir exists
  ansible.builtin.file: 
    path: /etc/wireguard
    state: directory
    owner: root
  register: config_dir

- name: Generate keys
  ansible.builtin.shell: wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
  when: config_dir.changed

- name: Ensure file permissions are set correctly
  ansible.builtin.file: 
    path: /etc/wireguard/privatekey
    mode: 0400
    state: file

- name: Configure interfaces
  include_tasks: wg_interface.yml
  vars:
    iface: "{{ item }}"
  with_items: "{{ wireguard.interfaces }}"
