---

- name: Ensure repo is enabled
  shell: dnf -y copr enable jdoss/wireguard

- name: Ensure wireguard is installed
  dnf: name={{ item }} state=installed
  with_items:
    - wireguard-dkms 
    - wireguard-tools

- name: Ensure config dir exists
  file: path=/etc/wireguard state=directory owner=root
  register: config_dir

- name: Generate keys
  shell: wg genkey | tee /etc/wireguard/privatekey | wg pubkey > /etc/wireguard/publickey
  when: config_dir.changed

- name: Ensure file permissions are set correctly
  file: path=/etc/wireguard/privatekey mode=0400 state=file

- name: Configure interfaces
  include_tasks: wg_interface.yml
  vars:
    iface: "{{ item }}"
  with_items: "{{ wireguard.interfaces }}"
