- name: Configure {{ item.name }}
  template: 
    src: wg.j2 
    dest: "/etc/wireguard/{{ iface.name }}.conf"
    owner: root 
    mode: 0600

- name: Ensure service is enabled and started
  service: name=wg-quick@{{ iface.name }} enabled=yes
  systemd:
    name: "wg-quick@{{ iface.name }}"
    enabled: yes
    state: started
