- name: Configure {{ item.name }}
  ansible.builtin.template:
    src: wg.j2 
    dest: "/etc/wireguard/{{ iface.name }}.conf"
    owner: root 
    mode: 0600

- name: Ensure service is enabled and started
  ansible.builtin.systemd:
    name: "wg-quick@{{ iface.name }}"
    enabled: true
    state: started
